### ISSUE TITLE
Broken on 8u161 and 8u162

### ISSUE THREAD

**Issue by wtlucy** [javaee/grizzly-npn#4]
This module is incompatible with the latest Java releases.  When attempting to run the 1.7 release on a 8u161 JVM, I hit the following NCDFE:

java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension

Compiling the source on an 8u162 JDK yields these errors:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project grizzly-npn-bootstrap: Compilation failure: Compilation failure:
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ServerHandshaker.java:[113,13] cannot find symbol
[ERROR] symbol:   class SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ServerHandshaker
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/HandshakeMessage.java:[1178,23] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.HandshakeMessage.ECDH_ServerKeyExchange
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/HandshakeMessage.java:[1216,21] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.HandshakeMessage.ECDH_ServerKeyExchange
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/HandshakeMessage.java:[1222,25] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.HandshakeMessage.ECDH_ServerKeyExchange
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ServerHandshaker.java:[766,32] cannot find symbol
[ERROR] symbol:   class SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ServerHandshaker
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ServerHandshaker.java:[796,23] no suitable constructor found for SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,java.security.SecureRandom,java.lang.String,int)
[ERROR] constructor sun.security.ssl.SSLSessionImpl.SSLSessionImpl() is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor sun.security.ssl.SSLSessionImpl.SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,java.security.SecureRandom,java.lang.String,int,boolean) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor sun.security.ssl.SSLSessionImpl.SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,sun.security.ssl.SessionId,java.lang.String,int,boolean) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ServerHandshaker.java:[1519,17] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ServerHandshaker
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ServerHandshaker.java:[1574,22] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ServerHandshaker
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ServerHandshaker.java:[1575,31] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ServerHandshaker
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/HelloExtensions.java:[97,33] cannot find symbol
[ERROR] symbol:   class SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.HelloExtensions
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/HelloExtensions.java:[100,29] cannot find symbol
[ERROR] symbol:   class SupportedEllipticPointFormatsExtension
[ERROR] location: class sun.security.ssl.HelloExtensions
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ClientHandshaker.java:[722,19] no suitable constructor found for SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,sun.security.ssl.SessionId,java.lang.String,int)
[ERROR] constructor sun.security.ssl.SSLSessionImpl.SSLSessionImpl() is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor sun.security.ssl.SSLSessionImpl.SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,java.security.SecureRandom,java.lang.String,int,boolean) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] constructor sun.security.ssl.SSLSessionImpl.SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,sun.security.ssl.SessionId,java.lang.String,int,boolean) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ClientHandshaker.java:[884,33] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ClientHandshaker
[ERROR] /home/user/grizzly-npn/bootstrap/src/main/java/sun/security/ssl/ClientHandshaker.java:[886,30] cannot find symbol
[ERROR] symbol:   variable SupportedEllipticCurvesExtension
[ERROR] location: class sun.security.ssl.ClientHandshaker`

It looks like a handful of internal SSL changes were made since this project has last been updated.  With these changes, everything compiles and runs fine on 8u162:

`SupportedEllipticCurvesExtension` -> `EllipticCurvesExtension` (renamed)
`SupportedEllipticPointFormatsExtension` -> `EllipticPointFormatsExtension` (renamed)
`SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,sun.security.ssl.SessionId,java.lang.String,int)` -> `SSLSessionImpl(sun.security.ssl.ProtocolVersion,sun.security.ssl.CipherSuite,java.util.Collection<sun.security.ssl.SignatureAndHashAlgorithm>,java.security.SecureRandom,java.lang.String,int,boolean) `(constructor changed)

**Comment by smillidge** [comment]
Issue also created on Eclipse Grizzly NPN  project https://github.com/eclipse-ee4j/grizzly-npn/issues/1

**Comment by ghost** [comment]
Resolved by PR #5
